name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env: # тег, под которым будет храниться временный образ-кеш
  TEST_TAG: plaatos/devops-example-app:test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2

      # Настройка QEMU для кросс-платформенной сборки
      - uses: docker/setup-qemu-action@v1

      # Настройка Buildx для улучшенной сборки
      - uses: docker/setup-buildx-action@v1

      # Логинимся в Docker Hub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Сборка и кеширование
      - uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      # Запуск тестов
      - run: docker run --rm ${{ env.TEST_TAG }} npm test

      # Заливаем протестированный образ на Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: plaatos/devops-example-app:latest