name: Release

on:
  create:
    tags:
      - v* # только теги начинающиеся с v: v1, v2, v5 

env:
  APP_IMAGE_NAME: plaatos/devops-example-app

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Скачиваем образ latest
      - run: docker pull ${{ env.APP_IMAGE_NAME }}:latest

      # Тегируем образ
      - run: docker tag ${{ env.APP_IMAGE_NAME }}:latest ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}

      # Логинимся в Docker Hub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Пушим новый тег
      - run: docker push ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}